// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module detect_face_cascade_classifier (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        integral_image_address0,
        integral_image_ce0,
        integral_image_q0,
        integral_image_address1,
        integral_image_ce1,
        integral_image_q1,
        height,
        width,
        factor,
        window_size,
        result_x1,
        result_x1_ap_vld,
        result_y1,
        result_y1_ap_vld,
        result_x2,
        result_x2_ap_vld,
        result_y2,
        result_y2_ap_vld,
        result_score_read,
        found,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_st1_fsm_0 = 16'b1;
parameter    ap_ST_st2_fsm_1 = 16'b10;
parameter    ap_ST_st3_fsm_2 = 16'b100;
parameter    ap_ST_st4_fsm_3 = 16'b1000;
parameter    ap_ST_st5_fsm_4 = 16'b10000;
parameter    ap_ST_st6_fsm_5 = 16'b100000;
parameter    ap_ST_st7_fsm_6 = 16'b1000000;
parameter    ap_ST_st8_fsm_7 = 16'b10000000;
parameter    ap_ST_pp0_stg0_fsm_8 = 16'b100000000;
parameter    ap_ST_pp0_stg1_fsm_9 = 16'b1000000000;
parameter    ap_ST_pp0_stg2_fsm_10 = 16'b10000000000;
parameter    ap_ST_pp0_stg3_fsm_11 = 16'b100000000000;
parameter    ap_ST_pp0_stg4_fsm_12 = 16'b1000000000000;
parameter    ap_ST_pp0_stg5_fsm_13 = 16'b10000000000000;
parameter    ap_ST_st17_fsm_14 = 16'b100000000000000;
parameter    ap_ST_st18_fsm_15 = 16'b1000000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_D = 32'b1101;
parameter    ap_const_lv32_E = 32'b1110;
parameter    ap_const_lv64_0 = 64'b0000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv26_0 = 26'b00000000000000000000000000;
parameter    ap_const_lv13_0 = 13'b0000000000000;
parameter    ap_const_lv5_0 = 5'b00000;
parameter    ap_const_lv21_0 = 21'b000000000000000000000;
parameter    ap_const_lv8_1 = 8'b1;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_FFFFFFE8 = 32'b11111111111111111111111111101000;
parameter    ap_const_lv64_1 = 64'b1;
parameter    ap_const_lv32_19 = 32'b11001;
parameter    ap_const_lv32_18 = 32'b11000;
parameter    ap_const_lv7_0 = 7'b0000000;
parameter    ap_const_lv16_18 = 16'b11000;
parameter    ap_const_lv5_19 = 5'b11001;
parameter    ap_const_lv5_1 = 5'b1;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_1E = 32'b11110;
parameter    ap_const_lv9_181 = 9'b110000001;
parameter    ap_const_lv8_7F = 8'b1111111;
parameter    ap_const_lv13_1 = 13'b1;
parameter    ap_const_lv8_0 = 8'b00000000;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [14:0] integral_image_address0;
output   integral_image_ce0;
input  [31:0] integral_image_q0;
output  [14:0] integral_image_address1;
output   integral_image_ce1;
input  [31:0] integral_image_q1;
input  [31:0] height;
input  [31:0] width;
input  [31:0] factor;
input  [31:0] window_size;
output  [7:0] result_x1;
output   result_x1_ap_vld;
output  [7:0] result_y1;
output   result_y1_ap_vld;
output  [7:0] result_x2;
output   result_x2_ap_vld;
output  [7:0] result_y2;
output   result_y2_ap_vld;
input  [31:0] result_score_read;
input  [7:0] found;
output  [7:0] ap_return_0;
output  [31:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[14:0] integral_image_address0;
reg integral_image_ce0;
reg[14:0] integral_image_address1;
reg integral_image_ce1;
reg result_x1_ap_vld;
reg result_y1_ap_vld;
reg result_x2_ap_vld;
reg result_y2_ap_vld;

(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_33;
wire   [4:0] STAGE_THRESH_address0;
reg    STAGE_THRESH_ce0;
wire   [10:0] STAGE_THRESH_q0;
wire   [4:0] STAGE_NUM_FEATURE_address0;
reg    STAGE_NUM_FEATURE_ce0;
wire   [7:0] STAGE_NUM_FEATURE_q0;
wire   [11:0] FEATURE_THRESH_address0;
reg    FEATURE_THRESH_ce0;
wire   [7:0] FEATURE_THRESH_q0;
wire   [11:0] FEATURE_ABOVE_address0;
reg    FEATURE_ABOVE_ce0;
wire   [12:0] FEATURE_ABOVE_q0;
wire   [11:0] FEATURE_BELOW_address0;
reg    FEATURE_BELOW_ce0;
wire   [12:0] FEATURE_BELOW_q0;
wire   [11:0] RECT1_X_address0;
reg    RECT1_X_ce0;
wire   [4:0] RECT1_X_q0;
wire   [11:0] RECT1_Y_address0;
reg    RECT1_Y_ce0;
wire   [4:0] RECT1_Y_q0;
wire   [11:0] RECT1_WIDTH_address0;
reg    RECT1_WIDTH_ce0;
wire   [4:0] RECT1_WIDTH_q0;
wire   [11:0] RECT1_HEIGHT_address0;
reg    RECT1_HEIGHT_ce0;
wire   [4:0] RECT1_HEIGHT_q0;
wire   [11:0] RECT1_WEIGHT_address0;
reg    RECT1_WEIGHT_ce0;
wire   [7:0] RECT1_WEIGHT_q0;
wire   [11:0] RECT2_X_address0;
reg    RECT2_X_ce0;
wire   [4:0] RECT2_X_q0;
wire   [11:0] RECT2_Y_address0;
reg    RECT2_Y_ce0;
wire   [4:0] RECT2_Y_q0;
wire   [11:0] RECT2_WIDTH_address0;
reg    RECT2_WIDTH_ce0;
wire   [4:0] RECT2_WIDTH_q0;
wire   [11:0] RECT2_HEIGHT_address0;
reg    RECT2_HEIGHT_ce0;
wire   [4:0] RECT2_HEIGHT_q0;
wire   [11:0] RECT2_WEIGHT_address0;
reg    RECT2_WEIGHT_ce0;
wire   [8:0] RECT2_WEIGHT_q0;
wire   [11:0] RECT3_X_address0;
reg    RECT3_X_ce0;
wire   [4:0] RECT3_X_q0;
wire   [11:0] RECT3_Y_address0;
reg    RECT3_Y_ce0;
wire   [4:0] RECT3_Y_q0;
wire   [11:0] RECT3_WIDTH_address0;
reg    RECT3_WIDTH_ce0;
wire   [3:0] RECT3_WIDTH_q0;
wire   [11:0] RECT3_HEIGHT_address0;
reg    RECT3_HEIGHT_ce0;
wire   [3:0] RECT3_HEIGHT_q0;
wire   [11:0] RECT3_WEIGHT_address0;
reg    RECT3_WEIGHT_ce0;
wire   [8:0] RECT3_WEIGHT_q0;
reg   [20:0] stage_accum_reg_677;
reg   [12:0] feature_index_1_reg_689;
wire   [31:0] grp_fu_708_p1;
reg   [31:0] reg_737;
reg    ap_sig_cseq_ST_st5_fsm_4;
reg    ap_sig_215;
reg    ap_sig_cseq_ST_st7_fsm_6;
reg    ap_sig_222;
wire   [0:0] tmp_35_fu_1054_p2;
wire   [31:0] tmp_fu_742_p2;
reg   [31:0] tmp_reg_1950;
wire   [7:0] tmp_116_fu_754_p1;
reg   [7:0] tmp_116_reg_1955;
wire   [63:0] bound_fu_766_p2;
reg   [63:0] bound_reg_1961;
wire   [63:0] indvar_flatten_next_fu_787_p2;
reg   [63:0] indvar_flatten_next_reg_1969;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_247;
wire   [31:0] col_mid2_fu_804_p3;
reg   [31:0] col_mid2_reg_1974;
wire   [0:0] exitcond_flatten_fu_782_p2;
wire   [31:0] tmp_45_mid2_v_fu_856_p3;
reg   [31:0] tmp_45_mid2_v_reg_1983;
wire   [15:0] tmp_79_fu_915_p2;
reg   [15:0] tmp_79_reg_1997;
wire   [15:0] tmp_81_fu_936_p2;
reg   [15:0] tmp_81_reg_2007;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_271;
reg  signed [31:0] D_reg_2017;
reg  signed [31:0] C_reg_2029;
wire   [31:0] tmp_34_fu_1040_p2;
reg   [31:0] tmp_34_reg_2036;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_284;
wire   [31:0] val_assign_3_mid2_fu_1046_p1;
reg   [31:0] val_assign_3_mid2_reg_2041;
reg    ap_sig_cseq_ST_st6_fsm_5;
reg    ap_sig_293;
wire    grp_detect_face_int_sqrt_fu_699_ap_done;
wire   [23:0] feature_thresh_trunc_ext_cast_fu_1050_p1;
reg   [23:0] feature_thresh_trunc_ext_cast_reg_2047;
reg   [0:0] tmp_35_reg_2052;
wire   [4:0] s_1_fu_1060_p2;
reg   [4:0] s_1_reg_2056;
wire   [7:0] tmp_87_fu_1178_p3;
reg   [7:0] tmp_87_reg_2071;
wire  signed [20:0] stage_thresh_cast_fu_1186_p1;
reg  signed [20:0] stage_thresh_cast_reg_2077;
reg    ap_sig_cseq_ST_st8_fsm_7;
reg    ap_sig_319;
wire   [12:0] feature_index_2_fu_1194_p2;
reg   [12:0] feature_index_2_reg_2082;
wire   [0:0] exitcond_fu_1200_p2;
reg   [0:0] exitcond_reg_2088;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_8;
reg    ap_sig_330;
reg    ap_reg_ppiten_pp0_it0;
reg    ap_reg_ppiten_pp0_it1;
reg   [0:0] ap_reg_ppstg_exitcond_reg_2088_pp0_iter1;
wire   [63:0] tmp_44_fu_1205_p1;
reg   [63:0] tmp_44_reg_2092;
wire   [12:0] tmp_61_fu_1213_p2;
reg   [12:0] tmp_61_reg_2130;
reg    ap_sig_cseq_ST_pp0_stg1_fsm_9;
reg    ap_sig_361;
wire   [15:0] tmp_92_fu_1347_p2;
reg   [15:0] tmp_92_reg_2165;
wire   [15:0] tmp_93_fu_1353_p2;
reg   [15:0] tmp_93_reg_2170;
reg    ap_sig_cseq_ST_pp0_stg2_fsm_10;
reg    ap_sig_386;
wire   [31:0] grp_fu_717_p2;
reg   [31:0] tmp_47_reg_2225;
wire   [15:0] tmp_98_fu_1487_p2;
reg   [15:0] tmp_98_reg_2240;
wire   [15:0] tmp_99_fu_1493_p2;
reg   [15:0] tmp_99_reg_2245;
reg  signed [7:0] FEATURE_THRESH_load_reg_2250;
reg    ap_sig_cseq_ST_pp0_stg3_fsm_11;
reg    ap_sig_425;
reg   [12:0] above_reg_2255;
reg   [12:0] below_reg_2260;
reg   [7:0] rect1_weight_reg_2265;
reg   [8:0] rect2_weight_reg_2270;
reg   [8:0] rect3_weight_reg_2275;
reg   [31:0] tmp_51_reg_2280;
wire   [15:0] tmp_104_fu_1627_p2;
reg   [15:0] tmp_104_reg_2295;
wire   [15:0] tmp_105_fu_1633_p2;
reg   [15:0] tmp_105_reg_2300;
reg    ap_sig_cseq_ST_pp0_stg4_fsm_12;
reg    ap_sig_451;
reg   [31:0] tmp_55_reg_2315;
reg    ap_sig_cseq_ST_pp0_stg5_fsm_13;
reg    ap_sig_466;
wire   [31:0] tmp_57_fu_1669_p2;
reg   [31:0] tmp_57_reg_2330;
wire   [31:0] tmp_58_fu_1697_p2;
reg   [31:0] tmp_58_reg_2345;
wire   [20:0] stage_accum_1_fu_1755_p2;
wire   [25:0] total_stage_accum_1_fu_1770_p2;
reg    ap_sig_cseq_ST_st17_fsm_14;
reg    ap_sig_492;
wire   [0:0] tmp_42_fu_1765_p2;
wire   [31:0] col_3_fu_1776_p2;
wire    grp_detect_face_int_sqrt_fu_699_ap_start;
wire    grp_detect_face_int_sqrt_fu_699_ap_idle;
wire    grp_detect_face_int_sqrt_fu_699_ap_ready;
wire   [15:0] grp_detect_face_int_sqrt_fu_699_ap_return;
reg   [63:0] indvar_flatten_reg_609;
reg   [31:0] row_reg_620;
reg   [31:0] col_reg_631;
reg   [25:0] total_stage_accum_reg_642;
reg   [12:0] feature_index_reg_654;
reg   [4:0] s_reg_666;
reg   [12:0] feature_index_1_phi_fu_692_p4;
reg    ap_reg_grp_detect_face_int_sqrt_fu_699_ap_start;
wire   [63:0] tmp_104_cast_fu_910_p1;
wire   [63:0] tmp_106_cast_fu_931_p1;
wire   [63:0] tmp_105_cast_fu_954_p1;
wire   [63:0] tmp_107_cast_fu_958_p1;
wire   [63:0] tmp_36_fu_1066_p1;
wire   [63:0] tmp_119_cast_fu_1297_p1;
wire   [63:0] tmp_123_cast_fu_1338_p1;
wire   [63:0] tmp_129_cast_fu_1437_p1;
wire   [63:0] tmp_133_cast_fu_1478_p1;
wire   [63:0] tmp_139_cast_fu_1577_p1;
wire   [63:0] tmp_143_cast_fu_1618_p1;
wire   [63:0] tmp_124_cast_fu_1639_p1;
wire   [63:0] tmp_125_cast_fu_1643_p1;
wire   [63:0] tmp_134_cast_fu_1661_p1;
wire   [63:0] tmp_135_cast_fu_1665_p1;
wire   [63:0] tmp_144_cast_fu_1689_p1;
wire   [63:0] tmp_145_cast_fu_1693_p1;
reg   [7:0] p_1_fu_162;
reg    ap_sig_cseq_ST_st18_fsm_15;
reg    ap_sig_569;
wire   [0:0] tmp_38_fu_1908_p2;
reg   [31:0] result_score_1_fu_166;
wire  signed [31:0] total_stage_accum_cast_fu_1781_p1;
wire   [0:0] tmp_41_fu_1914_p2;
wire   [7:0] tmp_84_fu_1898_p3;
reg   [31:0] grp_fu_708_p0;
wire   [31:0] tmp_s_fu_748_p2;
wire   [31:0] bound_fu_766_p0;
wire   [31:0] bound_fu_766_p1;
wire   [0:0] exitcond1_fu_799_p2;
wire   [31:0] tmp_44_mid2_v_v_cast_fu_812_p3;
wire   [31:0] tmp_44_mid2_v_fu_820_p2;
wire   [8:0] tmp_117_fu_826_p1;
wire   [10:0] tmp_120_fu_838_p1;
wire   [15:0] p_shl4_cast_fu_830_p3;
wire   [15:0] p_shl5_cast_fu_842_p3;
wire   [31:0] row_3_fu_793_p2;
wire   [8:0] tmp_121_fu_864_p1;
wire   [10:0] tmp_126_fu_876_p1;
wire   [15:0] p_shl2_cast_fu_868_p3;
wire   [15:0] p_shl3_cast_fu_880_p3;
wire   [15:0] tmp_127_fu_894_p1;
wire   [15:0] tmp_130_fu_898_p2;
wire   [15:0] tmp_76_fu_850_p2;
wire   [15:0] tmp_78_fu_904_p2;
wire   [15:0] tmp_77_fu_888_p2;
wire   [15:0] tmp_131_fu_921_p1;
wire   [15:0] tmp_80_fu_925_p2;
wire  signed [31:0] tmp_26_fu_970_p0;
wire  signed [31:0] tmp_26_fu_970_p1;
wire  signed [31:0] tmp_27_fu_976_p0;
wire  signed [31:0] tmp_27_fu_976_p1;
wire   [31:0] tmp_24_fu_962_p2;
wire   [31:0] tmp_25_fu_966_p2;
wire   [31:0] tmp_28_fu_982_p2;
wire   [31:0] tmp_27_fu_976_p2;
wire   [31:0] tmp_26_fu_970_p2;
wire   [31:0] tmp_29_fu_988_p2;
wire   [31:0] tmp_30_fu_1000_p2;
wire  signed [31:0] tmp_31_fu_1004_p1;
wire  signed [31:0] mean_fu_1010_p0;
wire   [31:0] tmp_31_fu_1004_p2;
wire   [31:0] stddev_fu_994_p2;
wire   [31:0] tmp_136_fu_1016_p2;
wire   [31:0] tmp_137_fu_1022_p2;
wire  signed [31:0] mean_fu_1010_p2;
wire   [31:0] tmp_32_fu_1028_p2;
wire   [31:0] tmp_33_fu_1034_p2;
wire   [31:0] grp_fu_704_p2;
wire   [22:0] loc_V_8_fu_1081_p1;
wire   [23:0] p_Result_9_fu_1084_p3;
wire   [7:0] loc_V_7_fu_1072_p4;
wire   [8:0] tmp_i_i_i6_cast2_fu_1096_p1;
wire   [8:0] sh_assign_2_fu_1100_p2;
wire   [7:0] tmp_1_i_i9_fu_1114_p2;
wire   [0:0] isNeg_3_fu_1106_p3;
wire  signed [8:0] tmp_1_i_i9_cast_fu_1120_p1;
wire   [8:0] sh_assign_3_fu_1124_p3;
wire  signed [31:0] sh_assign_3_cast_fu_1132_p1;
wire  signed [23:0] sh_assign_3_cast_cast_fu_1136_p1;
wire   [77:0] tmp_i_i5_fu_1092_p1;
wire   [77:0] tmp_2_i_i1_fu_1140_p1;
wire   [23:0] tmp_3_i_i1_fu_1144_p2;
wire   [0:0] tmp_149_fu_1156_p3;
wire   [77:0] tmp_5_i_i1_fu_1150_p2;
wire   [7:0] tmp_85_fu_1164_p1;
wire   [7:0] tmp_86_fu_1168_p4;
wire   [12:0] stage_feature_count_cast_fu_1190_p1;
wire   [31:0] RECT1_X_load_cast_fu_1219_p1;
wire   [31:0] RECT1_Y_load_cast_fu_1228_p1;
wire   [31:0] rect1_x1_fu_1223_p2;
wire   [31:0] RECT1_HEIGHT_load_cast_fu_1245_p1;
wire   [31:0] rect1_y1_fu_1232_p2;
wire   [15:0] tmp_151_fu_1241_p1;
wire   [15:0] tmp_150_fu_1237_p1;
wire   [31:0] rect1_y2_fu_1249_p2;
wire   [8:0] tmp_157_fu_1261_p1;
wire   [10:0] tmp_158_fu_1273_p1;
wire   [15:0] p_shl16_cast_fu_1265_p3;
wire   [15:0] p_shl17_cast_fu_1277_p3;
wire   [15:0] tmp_156_fu_1255_p2;
wire   [15:0] tmp_88_fu_1285_p2;
wire   [15:0] tmp_89_fu_1291_p2;
wire   [8:0] tmp_159_fu_1302_p1;
wire   [10:0] tmp_160_fu_1314_p1;
wire   [15:0] p_shl14_cast_fu_1306_p3;
wire   [15:0] p_shl15_cast_fu_1318_p3;
wire   [15:0] tmp_90_fu_1326_p2;
wire   [15:0] tmp_91_fu_1332_p2;
wire   [15:0] tmp_161_fu_1343_p1;
wire   [31:0] RECT2_X_load_cast_fu_1359_p1;
wire   [31:0] RECT2_Y_load_cast_fu_1368_p1;
wire   [31:0] rect2_x1_fu_1363_p2;
wire   [31:0] RECT2_HEIGHT_load_cast_fu_1385_p1;
wire   [31:0] rect2_y1_fu_1372_p2;
wire   [15:0] tmp_153_fu_1381_p1;
wire   [15:0] tmp_152_fu_1377_p1;
wire   [31:0] rect2_y2_fu_1389_p2;
wire   [8:0] tmp_163_fu_1401_p1;
wire   [10:0] tmp_164_fu_1413_p1;
wire   [15:0] p_shl12_cast_fu_1405_p3;
wire   [15:0] p_shl13_cast_fu_1417_p3;
wire   [15:0] tmp_162_fu_1395_p2;
wire   [15:0] tmp_94_fu_1425_p2;
wire   [15:0] tmp_95_fu_1431_p2;
wire   [8:0] tmp_165_fu_1442_p1;
wire   [10:0] tmp_166_fu_1454_p1;
wire   [15:0] p_shl10_cast_fu_1446_p3;
wire   [15:0] p_shl11_cast_fu_1458_p3;
wire   [15:0] tmp_96_fu_1466_p2;
wire   [15:0] tmp_97_fu_1472_p2;
wire   [15:0] tmp_167_fu_1483_p1;
wire   [31:0] RECT3_X_load_cast_fu_1499_p1;
wire   [31:0] RECT3_Y_load_cast_fu_1508_p1;
wire   [31:0] rect3_x1_fu_1503_p2;
wire   [31:0] RECT3_HEIGHT_load_cast_fu_1525_p1;
wire   [31:0] rect3_y1_fu_1512_p2;
wire   [15:0] tmp_155_fu_1521_p1;
wire   [15:0] tmp_154_fu_1517_p1;
wire   [31:0] rect3_y2_fu_1529_p2;
wire   [8:0] tmp_169_fu_1541_p1;
wire   [10:0] tmp_170_fu_1553_p1;
wire   [15:0] p_shl8_cast_fu_1545_p3;
wire   [15:0] p_shl9_cast_fu_1557_p3;
wire   [15:0] tmp_168_fu_1535_p2;
wire   [15:0] tmp_100_fu_1565_p2;
wire   [15:0] tmp_101_fu_1571_p2;
wire   [8:0] tmp_171_fu_1582_p1;
wire   [10:0] tmp_172_fu_1594_p1;
wire   [15:0] p_shl6_cast_fu_1586_p3;
wire   [15:0] p_shl7_cast_fu_1598_p3;
wire   [15:0] tmp_102_fu_1606_p2;
wire   [15:0] tmp_103_fu_1612_p2;
wire   [15:0] tmp_173_fu_1623_p1;
wire   [31:0] tmp_48_fu_1650_p2;
wire  signed [7:0] tmp_57_fu_1669_p0;
wire  signed [31:0] rect1_sum_fu_1655_p2;
wire   [31:0] tmp_52_fu_1678_p2;
wire   [8:0] tmp_58_fu_1697_p0;
wire  signed [31:0] rect2_sum_fu_1683_p2;
wire  signed [23:0] feature_thresh_fu_1925_p2;
wire   [31:0] tmp_56_fu_1712_p2;
wire   [8:0] tmp_59_fu_1723_p0;
wire  signed [31:0] rect3_sum_fu_1717_p2;
wire   [31:0] tmp_59_fu_1723_p2;
wire   [31:0] tmp1_fu_1729_p2;
wire   [31:0] rects_sum_fu_1734_p2;
wire  signed [31:0] feature_thresh_cast_fu_1706_p1;
wire   [0:0] tmp_60_fu_1739_p2;
wire   [12:0] below_1_fu_1745_p3;
wire  signed [20:0] below_1_cast_fu_1751_p1;
wire  signed [25:0] stage_accum_cast_cast_fu_1761_p1;
wire   [31:0] p_Val2_s_fu_1786_p1;
wire   [22:0] loc_V_6_fu_1800_p1;
wire   [23:0] p_Result_s_fu_1804_p3;
wire   [7:0] loc_V_fu_1790_p4;
wire   [8:0] tmp_i_i_i_cast3_fu_1816_p1;
wire   [8:0] sh_assign_fu_1820_p2;
wire   [7:0] tmp_1_i_i_fu_1834_p2;
wire   [0:0] isNeg_fu_1826_p3;
wire  signed [8:0] tmp_1_i_i_cast_fu_1840_p1;
wire   [8:0] sh_assign_1_fu_1844_p3;
wire  signed [31:0] sh_assign_1_cast_fu_1852_p1;
wire  signed [23:0] sh_assign_1_cast_cast_fu_1856_p1;
wire   [77:0] tmp_i_i_fu_1812_p1;
wire   [77:0] tmp_2_i_i_fu_1860_p1;
wire   [23:0] tmp_3_i_i_fu_1864_p2;
wire   [0:0] tmp_146_fu_1876_p3;
wire   [77:0] tmp_5_i_i_fu_1870_p2;
wire   [7:0] tmp_82_fu_1884_p1;
wire   [7:0] tmp_83_fu_1888_p4;
wire   [15:0] feature_thresh_fu_1925_p1;
reg   [15:0] ap_NS_fsm;
wire   [63:0] bound_fu_766_p00;
wire   [63:0] bound_fu_766_p10;
wire   [31:0] tmp_58_fu_1697_p00;
wire   [31:0] tmp_59_fu_1723_p00;

// power-on initialization
initial begin
#0 ap_CS_fsm = 16'b1;
#0 ap_reg_ppiten_pp0_it0 = 1'b0;
#0 ap_reg_ppiten_pp0_it1 = 1'b0;
#0 ap_reg_grp_detect_face_int_sqrt_fu_699_ap_start = 1'b0;
end

detect_face_cascade_classifier_STAGE_THRESH #(
    .DataWidth( 11 ),
    .AddressRange( 25 ),
    .AddressWidth( 5 ))
STAGE_THRESH_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(STAGE_THRESH_address0),
    .ce0(STAGE_THRESH_ce0),
    .q0(STAGE_THRESH_q0)
);

detect_face_cascade_classifier_STAGE_NUM_FEATURE #(
    .DataWidth( 8 ),
    .AddressRange( 25 ),
    .AddressWidth( 5 ))
STAGE_NUM_FEATURE_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(STAGE_NUM_FEATURE_address0),
    .ce0(STAGE_NUM_FEATURE_ce0),
    .q0(STAGE_NUM_FEATURE_q0)
);

detect_face_cascade_classifier_FEATURE_THRESH #(
    .DataWidth( 8 ),
    .AddressRange( 2913 ),
    .AddressWidth( 12 ))
FEATURE_THRESH_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FEATURE_THRESH_address0),
    .ce0(FEATURE_THRESH_ce0),
    .q0(FEATURE_THRESH_q0)
);

detect_face_cascade_classifier_FEATURE_ABOVE #(
    .DataWidth( 13 ),
    .AddressRange( 2913 ),
    .AddressWidth( 12 ))
FEATURE_ABOVE_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FEATURE_ABOVE_address0),
    .ce0(FEATURE_ABOVE_ce0),
    .q0(FEATURE_ABOVE_q0)
);

detect_face_cascade_classifier_FEATURE_BELOW #(
    .DataWidth( 13 ),
    .AddressRange( 2913 ),
    .AddressWidth( 12 ))
FEATURE_BELOW_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FEATURE_BELOW_address0),
    .ce0(FEATURE_BELOW_ce0),
    .q0(FEATURE_BELOW_q0)
);

detect_face_cascade_classifier_RECT1_X #(
    .DataWidth( 5 ),
    .AddressRange( 2913 ),
    .AddressWidth( 12 ))
RECT1_X_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(RECT1_X_address0),
    .ce0(RECT1_X_ce0),
    .q0(RECT1_X_q0)
);

detect_face_cascade_classifier_RECT1_Y #(
    .DataWidth( 5 ),
    .AddressRange( 2913 ),
    .AddressWidth( 12 ))
RECT1_Y_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(RECT1_Y_address0),
    .ce0(RECT1_Y_ce0),
    .q0(RECT1_Y_q0)
);

detect_face_cascade_classifier_RECT1_WIDTH #(
    .DataWidth( 5 ),
    .AddressRange( 2913 ),
    .AddressWidth( 12 ))
RECT1_WIDTH_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(RECT1_WIDTH_address0),
    .ce0(RECT1_WIDTH_ce0),
    .q0(RECT1_WIDTH_q0)
);

detect_face_cascade_classifier_RECT1_HEIGHT #(
    .DataWidth( 5 ),
    .AddressRange( 2913 ),
    .AddressWidth( 12 ))
RECT1_HEIGHT_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(RECT1_HEIGHT_address0),
    .ce0(RECT1_HEIGHT_ce0),
    .q0(RECT1_HEIGHT_q0)
);

detect_face_cascade_classifier_RECT1_WEIGHT #(
    .DataWidth( 8 ),
    .AddressRange( 2913 ),
    .AddressWidth( 12 ))
RECT1_WEIGHT_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(RECT1_WEIGHT_address0),
    .ce0(RECT1_WEIGHT_ce0),
    .q0(RECT1_WEIGHT_q0)
);

detect_face_cascade_classifier_RECT2_X #(
    .DataWidth( 5 ),
    .AddressRange( 2913 ),
    .AddressWidth( 12 ))
RECT2_X_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(RECT2_X_address0),
    .ce0(RECT2_X_ce0),
    .q0(RECT2_X_q0)
);

detect_face_cascade_classifier_RECT2_Y #(
    .DataWidth( 5 ),
    .AddressRange( 2913 ),
    .AddressWidth( 12 ))
RECT2_Y_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(RECT2_Y_address0),
    .ce0(RECT2_Y_ce0),
    .q0(RECT2_Y_q0)
);

detect_face_cascade_classifier_RECT2_WIDTH #(
    .DataWidth( 5 ),
    .AddressRange( 2913 ),
    .AddressWidth( 12 ))
RECT2_WIDTH_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(RECT2_WIDTH_address0),
    .ce0(RECT2_WIDTH_ce0),
    .q0(RECT2_WIDTH_q0)
);

detect_face_cascade_classifier_RECT2_HEIGHT #(
    .DataWidth( 5 ),
    .AddressRange( 2913 ),
    .AddressWidth( 12 ))
RECT2_HEIGHT_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(RECT2_HEIGHT_address0),
    .ce0(RECT2_HEIGHT_ce0),
    .q0(RECT2_HEIGHT_q0)
);

detect_face_cascade_classifier_RECT2_WEIGHT #(
    .DataWidth( 9 ),
    .AddressRange( 2913 ),
    .AddressWidth( 12 ))
RECT2_WEIGHT_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(RECT2_WEIGHT_address0),
    .ce0(RECT2_WEIGHT_ce0),
    .q0(RECT2_WEIGHT_q0)
);

detect_face_cascade_classifier_RECT3_X #(
    .DataWidth( 5 ),
    .AddressRange( 2913 ),
    .AddressWidth( 12 ))
RECT3_X_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(RECT3_X_address0),
    .ce0(RECT3_X_ce0),
    .q0(RECT3_X_q0)
);

detect_face_cascade_classifier_RECT3_Y #(
    .DataWidth( 5 ),
    .AddressRange( 2913 ),
    .AddressWidth( 12 ))
RECT3_Y_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(RECT3_Y_address0),
    .ce0(RECT3_Y_ce0),
    .q0(RECT3_Y_q0)
);

detect_face_cascade_classifier_RECT3_WIDTH #(
    .DataWidth( 4 ),
    .AddressRange( 2913 ),
    .AddressWidth( 12 ))
RECT3_WIDTH_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(RECT3_WIDTH_address0),
    .ce0(RECT3_WIDTH_ce0),
    .q0(RECT3_WIDTH_q0)
);

detect_face_cascade_classifier_RECT3_HEIGHT #(
    .DataWidth( 4 ),
    .AddressRange( 2913 ),
    .AddressWidth( 12 ))
RECT3_HEIGHT_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(RECT3_HEIGHT_address0),
    .ce0(RECT3_HEIGHT_ce0),
    .q0(RECT3_HEIGHT_q0)
);

detect_face_cascade_classifier_RECT3_WEIGHT #(
    .DataWidth( 9 ),
    .AddressRange( 2913 ),
    .AddressWidth( 12 ))
RECT3_WEIGHT_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(RECT3_WEIGHT_address0),
    .ce0(RECT3_WEIGHT_ce0),
    .q0(RECT3_WEIGHT_q0)
);

detect_face_int_sqrt grp_detect_face_int_sqrt_fu_699(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_detect_face_int_sqrt_fu_699_ap_start),
    .ap_done(grp_detect_face_int_sqrt_fu_699_ap_done),
    .ap_idle(grp_detect_face_int_sqrt_fu_699_ap_idle),
    .ap_ready(grp_detect_face_int_sqrt_fu_699_ap_ready),
    .value_r(tmp_34_reg_2036),
    .ap_return(grp_detect_face_int_sqrt_fu_699_ap_return)
);

detect_face_fmul_32ns_32ns_32_1_max_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
detect_face_fmul_32ns_32ns_32_1_max_dsp_U8(
    .din0(reg_737),
    .din1(factor),
    .dout(grp_fu_704_p2)
);

detect_face_uitofp_32ns_32_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
detect_face_uitofp_32ns_32_1_U9(
    .din0(grp_fu_708_p0),
    .dout(grp_fu_708_p1)
);

detect_face_mul_mul_8s_16ns_24_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
detect_face_mul_mul_8s_16ns_24_1_U10(
    .din0(FEATURE_THRESH_load_reg_2250),
    .din1(feature_thresh_fu_1925_p1),
    .dout(feature_thresh_fu_1925_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_detect_face_int_sqrt_fu_699_ap_start <= 1'b0;
    end else begin
        if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
            ap_reg_grp_detect_face_int_sqrt_fu_699_ap_start <= 1'b1;
        end else if ((1'b1 == grp_detect_face_int_sqrt_fu_699_ap_ready)) begin
            ap_reg_grp_detect_face_int_sqrt_fu_699_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_8) & ~(1'b0 == exitcond_fu_1200_p2))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b0;
        end else if ((1'b1 == ap_sig_cseq_ST_st8_fsm_7)) begin
            ap_reg_ppiten_pp0_it0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= 1'b0;
    end else begin
        if (((1'b0 == exitcond_reg_2088) & (1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_13))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b1;
        end else if (((1'b1 == ap_sig_cseq_ST_st8_fsm_7) | ((1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_13) & ~(1'b0 == exitcond_reg_2088)))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st17_fsm_14) & ((1'b0 == tmp_35_reg_2052) | ~(1'b0 == tmp_42_fu_1765_p2)))) begin
        col_reg_631 <= col_3_fu_1776_p2;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        col_reg_631 <= ap_const_lv32_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_8) & (1'b1 == ap_reg_ppiten_pp0_it1) & (1'b0 == exitcond_reg_2088))) begin
        feature_index_1_reg_689 <= tmp_61_reg_2130;
    end else if ((1'b1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        feature_index_1_reg_689 <= feature_index_reg_654;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st17_fsm_14) & ~(1'b0 == tmp_35_reg_2052) & (1'b0 == tmp_42_fu_1765_p2))) begin
        feature_index_reg_654 <= feature_index_2_reg_2082;
    end else if (((1'b1 == ap_sig_cseq_ST_st6_fsm_5) & ~(1'b0 == grp_detect_face_int_sqrt_fu_699_ap_done))) begin
        feature_index_reg_654 <= ap_const_lv13_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st17_fsm_14) & ((1'b0 == tmp_35_reg_2052) | ~(1'b0 == tmp_42_fu_1765_p2)))) begin
        indvar_flatten_reg_609 <= indvar_flatten_next_reg_1969;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        indvar_flatten_reg_609 <= ap_const_lv64_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st18_fsm_15) & ~(1'b0 == tmp_38_fu_1908_p2))) begin
        p_1_fu_162 <= ap_const_lv8_1;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        p_1_fu_162 <= found;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_sig_cseq_ST_st18_fsm_15) & ~(1'b0 == tmp_38_fu_1908_p2)) | ((1'b1 == ap_sig_cseq_ST_st18_fsm_15) & (1'b0 == tmp_38_fu_1908_p2) & ~(1'b0 == tmp_41_fu_1914_p2)))) begin
        result_score_1_fu_166 <= total_stage_accum_cast_fu_1781_p1;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        result_score_1_fu_166 <= result_score_read;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st17_fsm_14) & ((1'b0 == tmp_35_reg_2052) | ~(1'b0 == tmp_42_fu_1765_p2)))) begin
        row_reg_620 <= tmp_45_mid2_v_reg_1983;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        row_reg_620 <= ap_const_lv32_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st17_fsm_14) & ~(1'b0 == tmp_35_reg_2052) & (1'b0 == tmp_42_fu_1765_p2))) begin
        s_reg_666 <= s_1_reg_2056;
    end else if (((1'b1 == ap_sig_cseq_ST_st6_fsm_5) & ~(1'b0 == grp_detect_face_int_sqrt_fu_699_ap_done))) begin
        s_reg_666 <= ap_const_lv5_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_9) & (1'b0 == ap_reg_ppstg_exitcond_reg_2088_pp0_iter1))) begin
        stage_accum_reg_677 <= stage_accum_1_fu_1755_p2;
    end else if ((1'b1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        stage_accum_reg_677 <= ap_const_lv21_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st17_fsm_14) & ~(1'b0 == tmp_35_reg_2052) & (1'b0 == tmp_42_fu_1765_p2))) begin
        total_stage_accum_reg_642 <= total_stage_accum_1_fu_1770_p2;
    end else if (((1'b1 == ap_sig_cseq_ST_st6_fsm_5) & ~(1'b0 == grp_detect_face_int_sqrt_fu_699_ap_done))) begin
        total_stage_accum_reg_642 <= ap_const_lv26_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        C_reg_2029 <= integral_image_q1;
        D_reg_2017 <= integral_image_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == exitcond_reg_2088) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_11))) begin
        FEATURE_THRESH_load_reg_2250 <= FEATURE_THRESH_q0;
        above_reg_2255 <= FEATURE_ABOVE_q0;
        below_reg_2260 <= FEATURE_BELOW_q0;
        rect1_weight_reg_2265 <= RECT1_WEIGHT_q0;
        rect2_weight_reg_2270 <= RECT2_WEIGHT_q0;
        rect3_weight_reg_2275 <= RECT3_WEIGHT_q0;
        tmp_104_reg_2295 <= tmp_104_fu_1627_p2;
        tmp_105_reg_2300 <= tmp_105_fu_1633_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_8)) begin
        ap_reg_ppstg_exitcond_reg_2088_pp0_iter1 <= exitcond_reg_2088;
        exitcond_reg_2088 <= exitcond_fu_1200_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        bound_reg_1961 <= bound_fu_766_p2;
        tmp_116_reg_1955 <= tmp_116_fu_754_p1;
        tmp_reg_1950 <= tmp_fu_742_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond_flatten_fu_782_p2))) begin
        col_mid2_reg_1974 <= col_mid2_fu_804_p3;
        tmp_45_mid2_v_reg_1983 <= tmp_45_mid2_v_fu_856_p3;
        tmp_79_reg_1997 <= tmp_79_fu_915_p2;
        tmp_81_reg_2007 <= tmp_81_fu_936_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        feature_index_2_reg_2082 <= feature_index_2_fu_1194_p2;
        stage_thresh_cast_reg_2077 <= stage_thresh_cast_fu_1186_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st6_fsm_5) & ~(1'b0 == grp_detect_face_int_sqrt_fu_699_ap_done))) begin
        feature_thresh_trunc_ext_cast_reg_2047[15 : 0] <= feature_thresh_trunc_ext_cast_fu_1050_p1[15 : 0];
        val_assign_3_mid2_reg_2041 <= val_assign_3_mid2_fu_1046_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        indvar_flatten_next_reg_1969 <= indvar_flatten_next_fu_787_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st5_fsm_4) | ((1'b1 == ap_sig_cseq_ST_st7_fsm_6) & (tmp_35_fu_1054_p2 == 1'b0)))) begin
        reg_737 <= grp_fu_708_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        s_1_reg_2056 <= s_1_fu_1060_p2;
        tmp_35_reg_2052 <= tmp_35_fu_1054_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        tmp_34_reg_2036 <= tmp_34_fu_1040_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_8) & (1'b0 == exitcond_fu_1200_p2))) begin
        tmp_44_reg_2092[12 : 0] <= tmp_44_fu_1205_p1[12 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == exitcond_reg_2088) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_10))) begin
        tmp_47_reg_2225 <= grp_fu_717_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == exitcond_reg_2088) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_11))) begin
        tmp_51_reg_2280 <= grp_fu_717_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == exitcond_reg_2088) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_12))) begin
        tmp_55_reg_2315 <= grp_fu_717_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == exitcond_reg_2088) & (1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_13))) begin
        tmp_57_reg_2330 <= tmp_57_fu_1669_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_8) & (1'b0 == exitcond_reg_2088))) begin
        tmp_58_reg_2345 <= tmp_58_fu_1697_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_8) & (1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == exitcond_fu_1200_p2))) begin
        tmp_61_reg_2130 <= tmp_61_fu_1213_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st7_fsm_6) & (tmp_35_fu_1054_p2 == 1'b0))) begin
        tmp_87_reg_2071 <= tmp_87_fu_1178_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_9) & (1'b0 == exitcond_reg_2088))) begin
        tmp_92_reg_2165 <= tmp_92_fu_1347_p2;
        tmp_93_reg_2170 <= tmp_93_fu_1353_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == exitcond_reg_2088) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_10))) begin
        tmp_98_reg_2240 <= tmp_98_fu_1487_p2;
        tmp_99_reg_2245 <= tmp_99_fu_1493_p2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_10))) begin
        FEATURE_ABOVE_ce0 = 1'b1;
    end else begin
        FEATURE_ABOVE_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_10))) begin
        FEATURE_BELOW_ce0 = 1'b1;
    end else begin
        FEATURE_BELOW_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_10))) begin
        FEATURE_THRESH_ce0 = 1'b1;
    end else begin
        FEATURE_THRESH_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_8) & (1'b1 == ap_reg_ppiten_pp0_it0))) begin
        RECT1_HEIGHT_ce0 = 1'b1;
    end else begin
        RECT1_HEIGHT_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_10))) begin
        RECT1_WEIGHT_ce0 = 1'b1;
    end else begin
        RECT1_WEIGHT_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_8) & (1'b1 == ap_reg_ppiten_pp0_it0))) begin
        RECT1_WIDTH_ce0 = 1'b1;
    end else begin
        RECT1_WIDTH_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_8) & (1'b1 == ap_reg_ppiten_pp0_it0))) begin
        RECT1_X_ce0 = 1'b1;
    end else begin
        RECT1_X_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_8) & (1'b1 == ap_reg_ppiten_pp0_it0))) begin
        RECT1_Y_ce0 = 1'b1;
    end else begin
        RECT1_Y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_9))) begin
        RECT2_HEIGHT_ce0 = 1'b1;
    end else begin
        RECT2_HEIGHT_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_10))) begin
        RECT2_WEIGHT_ce0 = 1'b1;
    end else begin
        RECT2_WEIGHT_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_9))) begin
        RECT2_WIDTH_ce0 = 1'b1;
    end else begin
        RECT2_WIDTH_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_9))) begin
        RECT2_X_ce0 = 1'b1;
    end else begin
        RECT2_X_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_9))) begin
        RECT2_Y_ce0 = 1'b1;
    end else begin
        RECT2_Y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_10))) begin
        RECT3_HEIGHT_ce0 = 1'b1;
    end else begin
        RECT3_HEIGHT_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_10))) begin
        RECT3_WEIGHT_ce0 = 1'b1;
    end else begin
        RECT3_WEIGHT_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_10))) begin
        RECT3_WIDTH_ce0 = 1'b1;
    end else begin
        RECT3_WIDTH_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_10))) begin
        RECT3_X_ce0 = 1'b1;
    end else begin
        RECT3_X_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_10))) begin
        RECT3_Y_ce0 = 1'b1;
    end else begin
        RECT3_Y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        STAGE_NUM_FEATURE_ce0 = 1'b1;
    end else begin
        STAGE_NUM_FEATURE_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        STAGE_THRESH_ce0 = 1'b1;
    end else begin
        STAGE_THRESH_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0)) | ((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond_flatten_fu_782_p2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond_flatten_fu_782_p2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_330) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_8 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_8 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_361) begin
        ap_sig_cseq_ST_pp0_stg1_fsm_9 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg1_fsm_9 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_386) begin
        ap_sig_cseq_ST_pp0_stg2_fsm_10 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg2_fsm_10 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_425) begin
        ap_sig_cseq_ST_pp0_stg3_fsm_11 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg3_fsm_11 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_451) begin
        ap_sig_cseq_ST_pp0_stg4_fsm_12 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg4_fsm_12 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_466) begin
        ap_sig_cseq_ST_pp0_stg5_fsm_13 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg5_fsm_13 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_492) begin
        ap_sig_cseq_ST_st17_fsm_14 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st17_fsm_14 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_569) begin
        ap_sig_cseq_ST_st18_fsm_15 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st18_fsm_15 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_33) begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_247) begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_271) begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_284) begin
        ap_sig_cseq_ST_st4_fsm_3 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_215) begin
        ap_sig_cseq_ST_st5_fsm_4 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_4 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_293) begin
        ap_sig_cseq_ST_st6_fsm_5 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_5 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_222) begin
        ap_sig_cseq_ST_st7_fsm_6 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_6 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_319) begin
        ap_sig_cseq_ST_st8_fsm_7 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_8) & (1'b1 == ap_reg_ppiten_pp0_it1) & (1'b0 == exitcond_reg_2088))) begin
        feature_index_1_phi_fu_692_p4 = tmp_61_reg_2130;
    end else begin
        feature_index_1_phi_fu_692_p4 = feature_index_1_reg_689;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        grp_fu_708_p0 = col_mid2_reg_1974;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        grp_fu_708_p0 = tmp_45_mid2_v_reg_1983;
    end else begin
        grp_fu_708_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_8) & (1'b1 == ap_reg_ppiten_pp0_it1))) begin
        integral_image_address0 = tmp_144_cast_fu_1689_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_13))) begin
        integral_image_address0 = tmp_134_cast_fu_1661_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_12))) begin
        integral_image_address0 = tmp_124_cast_fu_1639_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_11))) begin
        integral_image_address0 = tmp_139_cast_fu_1577_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_10))) begin
        integral_image_address0 = tmp_129_cast_fu_1437_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_9))) begin
        integral_image_address0 = tmp_119_cast_fu_1297_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        integral_image_address0 = tmp_105_cast_fu_954_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        integral_image_address0 = tmp_104_cast_fu_910_p1;
    end else begin
        integral_image_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_8) & (1'b1 == ap_reg_ppiten_pp0_it1))) begin
        integral_image_address1 = tmp_145_cast_fu_1693_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_13))) begin
        integral_image_address1 = tmp_135_cast_fu_1665_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_12))) begin
        integral_image_address1 = tmp_125_cast_fu_1643_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_11))) begin
        integral_image_address1 = tmp_143_cast_fu_1618_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_10))) begin
        integral_image_address1 = tmp_133_cast_fu_1478_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_9))) begin
        integral_image_address1 = tmp_123_cast_fu_1338_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        integral_image_address1 = tmp_107_cast_fu_958_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        integral_image_address1 = tmp_106_cast_fu_931_p1;
    end else begin
        integral_image_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) | (1'b1 == ap_sig_cseq_ST_st3_fsm_2) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_10)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_11)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_12)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_8) & (1'b1 == ap_reg_ppiten_pp0_it1)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_9)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_13)))) begin
        integral_image_ce0 = 1'b1;
    end else begin
        integral_image_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) | (1'b1 == ap_sig_cseq_ST_st3_fsm_2) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_10)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_11)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_12)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_8) & (1'b1 == ap_reg_ppiten_pp0_it1)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_9)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg5_fsm_13)))) begin
        integral_image_ce1 = 1'b1;
    end else begin
        integral_image_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_st18_fsm_15) & ~(1'b0 == tmp_38_fu_1908_p2)) | ((1'b1 == ap_sig_cseq_ST_st18_fsm_15) & (1'b0 == tmp_38_fu_1908_p2) & ~(1'b0 == tmp_41_fu_1914_p2)))) begin
        result_x1_ap_vld = 1'b1;
    end else begin
        result_x1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_st18_fsm_15) & ~(1'b0 == tmp_38_fu_1908_p2)) | ((1'b1 == ap_sig_cseq_ST_st18_fsm_15) & (1'b0 == tmp_38_fu_1908_p2) & ~(1'b0 == tmp_41_fu_1914_p2)))) begin
        result_x2_ap_vld = 1'b1;
    end else begin
        result_x2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_st18_fsm_15) & ~(1'b0 == tmp_38_fu_1908_p2)) | ((1'b1 == ap_sig_cseq_ST_st18_fsm_15) & (1'b0 == tmp_38_fu_1908_p2) & ~(1'b0 == tmp_41_fu_1914_p2)))) begin
        result_y1_ap_vld = 1'b1;
    end else begin
        result_y1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_st18_fsm_15) & ~(1'b0 == tmp_38_fu_1908_p2)) | ((1'b1 == ap_sig_cseq_ST_st18_fsm_15) & (1'b0 == tmp_38_fu_1908_p2) & ~(1'b0 == tmp_41_fu_1914_p2)))) begin
        result_y2_ap_vld = 1'b1;
    end else begin
        result_y2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : begin
            if (~(1'b0 == exitcond_flatten_fu_782_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        end
        ap_ST_st3_fsm_2 : begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st4_fsm_3 : begin
            ap_NS_fsm = ap_ST_st5_fsm_4;
        end
        ap_ST_st5_fsm_4 : begin
            ap_NS_fsm = ap_ST_st6_fsm_5;
        end
        ap_ST_st6_fsm_5 : begin
            if (~(1'b0 == grp_detect_face_int_sqrt_fu_699_ap_done)) begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end else begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end
        end
        ap_ST_st7_fsm_6 : begin
            if ((tmp_35_fu_1054_p2 == 1'b0)) begin
                ap_NS_fsm = ap_ST_st18_fsm_15;
            end else begin
                ap_NS_fsm = ap_ST_st8_fsm_7;
            end
        end
        ap_ST_st8_fsm_7 : begin
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_8;
        end
        ap_ST_pp0_stg0_fsm_8 : begin
            if (~((1'b1 == ap_reg_ppiten_pp0_it0) & ~(1'b0 == exitcond_fu_1200_p2) & ~(1'b1 == ap_reg_ppiten_pp0_it1))) begin
                ap_NS_fsm = ap_ST_pp0_stg1_fsm_9;
            end else begin
                ap_NS_fsm = ap_ST_st17_fsm_14;
            end
        end
        ap_ST_pp0_stg1_fsm_9 : begin
            if (~((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_9) & ~(1'b1 == ap_reg_ppiten_pp0_it0))) begin
                ap_NS_fsm = ap_ST_pp0_stg2_fsm_10;
            end else begin
                ap_NS_fsm = ap_ST_st17_fsm_14;
            end
        end
        ap_ST_pp0_stg2_fsm_10 : begin
            ap_NS_fsm = ap_ST_pp0_stg3_fsm_11;
        end
        ap_ST_pp0_stg3_fsm_11 : begin
            ap_NS_fsm = ap_ST_pp0_stg4_fsm_12;
        end
        ap_ST_pp0_stg4_fsm_12 : begin
            ap_NS_fsm = ap_ST_pp0_stg5_fsm_13;
        end
        ap_ST_pp0_stg5_fsm_13 : begin
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_8;
        end
        ap_ST_st17_fsm_14 : begin
            if (((1'b0 == tmp_35_reg_2052) | ~(1'b0 == tmp_42_fu_1765_p2))) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end
        end
        ap_ST_st18_fsm_15 : begin
            ap_NS_fsm = ap_ST_st17_fsm_14;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign FEATURE_ABOVE_address0 = tmp_44_reg_2092;

assign FEATURE_BELOW_address0 = tmp_44_reg_2092;

assign FEATURE_THRESH_address0 = tmp_44_reg_2092;

assign RECT1_HEIGHT_address0 = tmp_44_fu_1205_p1;

assign RECT1_HEIGHT_load_cast_fu_1245_p1 = RECT1_HEIGHT_q0;

assign RECT1_WEIGHT_address0 = tmp_44_reg_2092;

assign RECT1_WIDTH_address0 = tmp_44_fu_1205_p1;

assign RECT1_X_address0 = tmp_44_fu_1205_p1;

assign RECT1_X_load_cast_fu_1219_p1 = RECT1_X_q0;

assign RECT1_Y_address0 = tmp_44_fu_1205_p1;

assign RECT1_Y_load_cast_fu_1228_p1 = RECT1_Y_q0;

assign RECT2_HEIGHT_address0 = tmp_44_reg_2092;

assign RECT2_HEIGHT_load_cast_fu_1385_p1 = RECT2_HEIGHT_q0;

assign RECT2_WEIGHT_address0 = tmp_44_reg_2092;

assign RECT2_WIDTH_address0 = tmp_44_reg_2092;

assign RECT2_X_address0 = tmp_44_reg_2092;

assign RECT2_X_load_cast_fu_1359_p1 = RECT2_X_q0;

assign RECT2_Y_address0 = tmp_44_reg_2092;

assign RECT2_Y_load_cast_fu_1368_p1 = RECT2_Y_q0;

assign RECT3_HEIGHT_address0 = tmp_44_reg_2092;

assign RECT3_HEIGHT_load_cast_fu_1525_p1 = RECT3_HEIGHT_q0;

assign RECT3_WEIGHT_address0 = tmp_44_reg_2092;

assign RECT3_WIDTH_address0 = tmp_44_reg_2092;

assign RECT3_X_address0 = tmp_44_reg_2092;

assign RECT3_X_load_cast_fu_1499_p1 = RECT3_X_q0;

assign RECT3_Y_address0 = tmp_44_reg_2092;

assign RECT3_Y_load_cast_fu_1508_p1 = RECT3_Y_q0;

assign STAGE_NUM_FEATURE_address0 = tmp_36_fu_1066_p1;

assign STAGE_THRESH_address0 = tmp_36_fu_1066_p1;

assign ap_return_0 = p_1_fu_162;

assign ap_return_1 = result_score_1_fu_166;

always @ (*) begin
    ap_sig_215 = (1'b1 == ap_CS_fsm[ap_const_lv32_4]);
end

always @ (*) begin
    ap_sig_222 = (1'b1 == ap_CS_fsm[ap_const_lv32_6]);
end

always @ (*) begin
    ap_sig_247 = (1'b1 == ap_CS_fsm[ap_const_lv32_1]);
end

always @ (*) begin
    ap_sig_271 = (1'b1 == ap_CS_fsm[ap_const_lv32_2]);
end

always @ (*) begin
    ap_sig_284 = (1'b1 == ap_CS_fsm[ap_const_lv32_3]);
end

always @ (*) begin
    ap_sig_293 = (1'b1 == ap_CS_fsm[ap_const_lv32_5]);
end

always @ (*) begin
    ap_sig_319 = (1'b1 == ap_CS_fsm[ap_const_lv32_7]);
end

always @ (*) begin
    ap_sig_33 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

always @ (*) begin
    ap_sig_330 = (1'b1 == ap_CS_fsm[ap_const_lv32_8]);
end

always @ (*) begin
    ap_sig_361 = (1'b1 == ap_CS_fsm[ap_const_lv32_9]);
end

always @ (*) begin
    ap_sig_386 = (1'b1 == ap_CS_fsm[ap_const_lv32_A]);
end

always @ (*) begin
    ap_sig_425 = (1'b1 == ap_CS_fsm[ap_const_lv32_B]);
end

always @ (*) begin
    ap_sig_451 = (1'b1 == ap_CS_fsm[ap_const_lv32_C]);
end

always @ (*) begin
    ap_sig_466 = (1'b1 == ap_CS_fsm[ap_const_lv32_D]);
end

always @ (*) begin
    ap_sig_492 = (1'b1 == ap_CS_fsm[ap_const_lv32_E]);
end

always @ (*) begin
    ap_sig_569 = (1'b1 == ap_CS_fsm[ap_const_lv32_F]);
end

assign below_1_cast_fu_1751_p1 = $signed(below_1_fu_1745_p3);

assign below_1_fu_1745_p3 = ((tmp_60_fu_1739_p2[0:0] === 1'b1) ? below_reg_2260 : above_reg_2255);

assign bound_fu_766_p0 = bound_fu_766_p00;

assign bound_fu_766_p00 = tmp_fu_742_p2;

assign bound_fu_766_p1 = bound_fu_766_p10;

assign bound_fu_766_p10 = tmp_s_fu_748_p2;

assign bound_fu_766_p2 = (bound_fu_766_p0 * bound_fu_766_p1);

assign col_3_fu_1776_p2 = (col_mid2_reg_1974 + ap_const_lv32_1);

assign col_mid2_fu_804_p3 = ((exitcond1_fu_799_p2[0:0] === 1'b1) ? ap_const_lv32_0 : col_reg_631);

assign exitcond1_fu_799_p2 = ((col_reg_631 == tmp_reg_1950) ? 1'b1 : 1'b0);

assign exitcond_flatten_fu_782_p2 = ((indvar_flatten_reg_609 == bound_reg_1961) ? 1'b1 : 1'b0);

assign exitcond_fu_1200_p2 = ((feature_index_1_phi_fu_692_p4 == feature_index_2_reg_2082) ? 1'b1 : 1'b0);

assign feature_index_2_fu_1194_p2 = (stage_feature_count_cast_fu_1190_p1 + feature_index_reg_654);

assign feature_thresh_cast_fu_1706_p1 = feature_thresh_fu_1925_p2;

assign feature_thresh_fu_1925_p1 = feature_thresh_trunc_ext_cast_reg_2047;

assign feature_thresh_trunc_ext_cast_fu_1050_p1 = grp_detect_face_int_sqrt_fu_699_ap_return;

assign grp_detect_face_int_sqrt_fu_699_ap_start = ap_reg_grp_detect_face_int_sqrt_fu_699_ap_start;

assign grp_fu_717_p2 = (integral_image_q0 - integral_image_q1);

assign indvar_flatten_next_fu_787_p2 = (indvar_flatten_reg_609 + ap_const_lv64_1);

assign isNeg_3_fu_1106_p3 = sh_assign_2_fu_1100_p2[ap_const_lv32_8];

assign isNeg_fu_1826_p3 = sh_assign_fu_1820_p2[ap_const_lv32_8];

assign loc_V_6_fu_1800_p1 = p_Val2_s_fu_1786_p1[22:0];

assign loc_V_7_fu_1072_p4 = {{val_assign_3_mid2_reg_2041[ap_const_lv32_1E : ap_const_lv32_17]}};

assign loc_V_8_fu_1081_p1 = val_assign_3_mid2_reg_2041[22:0];

assign loc_V_fu_1790_p4 = {{p_Val2_s_fu_1786_p1[ap_const_lv32_1E : ap_const_lv32_17]}};

assign mean_fu_1010_p0 = integral_image_q1;

assign mean_fu_1010_p2 = ($signed(mean_fu_1010_p0) + $signed(tmp_31_fu_1004_p2));

assign p_Result_9_fu_1084_p3 = {{1'b1}, {loc_V_8_fu_1081_p1}};

assign p_Result_s_fu_1804_p3 = {{1'b1}, {loc_V_6_fu_1800_p1}};

assign p_Val2_s_fu_1786_p1 = grp_fu_704_p2;

assign p_shl10_cast_fu_1446_p3 = {{tmp_165_fu_1442_p1}, {ap_const_lv7_0}};

assign p_shl11_cast_fu_1458_p3 = {{tmp_166_fu_1454_p1}, {ap_const_lv5_0}};

assign p_shl12_cast_fu_1405_p3 = {{tmp_163_fu_1401_p1}, {ap_const_lv7_0}};

assign p_shl13_cast_fu_1417_p3 = {{tmp_164_fu_1413_p1}, {ap_const_lv5_0}};

assign p_shl14_cast_fu_1306_p3 = {{tmp_159_fu_1302_p1}, {ap_const_lv7_0}};

assign p_shl15_cast_fu_1318_p3 = {{tmp_160_fu_1314_p1}, {ap_const_lv5_0}};

assign p_shl16_cast_fu_1265_p3 = {{tmp_157_fu_1261_p1}, {ap_const_lv7_0}};

assign p_shl17_cast_fu_1277_p3 = {{tmp_158_fu_1273_p1}, {ap_const_lv5_0}};

assign p_shl2_cast_fu_868_p3 = {{tmp_121_fu_864_p1}, {ap_const_lv7_0}};

assign p_shl3_cast_fu_880_p3 = {{tmp_126_fu_876_p1}, {ap_const_lv5_0}};

assign p_shl4_cast_fu_830_p3 = {{tmp_117_fu_826_p1}, {ap_const_lv7_0}};

assign p_shl5_cast_fu_842_p3 = {{tmp_120_fu_838_p1}, {ap_const_lv5_0}};

assign p_shl6_cast_fu_1586_p3 = {{tmp_171_fu_1582_p1}, {ap_const_lv7_0}};

assign p_shl7_cast_fu_1598_p3 = {{tmp_172_fu_1594_p1}, {ap_const_lv5_0}};

assign p_shl8_cast_fu_1545_p3 = {{tmp_169_fu_1541_p1}, {ap_const_lv7_0}};

assign p_shl9_cast_fu_1557_p3 = {{tmp_170_fu_1553_p1}, {ap_const_lv5_0}};

assign rect1_sum_fu_1655_p2 = (tmp_48_fu_1650_p2 - integral_image_q1);

assign rect1_x1_fu_1223_p2 = (RECT1_X_load_cast_fu_1219_p1 + col_mid2_reg_1974);

assign rect1_y1_fu_1232_p2 = (RECT1_Y_load_cast_fu_1228_p1 + tmp_45_mid2_v_reg_1983);

assign rect1_y2_fu_1249_p2 = (RECT1_HEIGHT_load_cast_fu_1245_p1 + rect1_y1_fu_1232_p2);

assign rect2_sum_fu_1683_p2 = (tmp_52_fu_1678_p2 - integral_image_q1);

assign rect2_x1_fu_1363_p2 = (RECT2_X_load_cast_fu_1359_p1 + col_mid2_reg_1974);

assign rect2_y1_fu_1372_p2 = (RECT2_Y_load_cast_fu_1368_p1 + tmp_45_mid2_v_reg_1983);

assign rect2_y2_fu_1389_p2 = (RECT2_HEIGHT_load_cast_fu_1385_p1 + rect2_y1_fu_1372_p2);

assign rect3_sum_fu_1717_p2 = (tmp_56_fu_1712_p2 - integral_image_q1);

assign rect3_x1_fu_1503_p2 = (RECT3_X_load_cast_fu_1499_p1 + col_mid2_reg_1974);

assign rect3_y1_fu_1512_p2 = (RECT3_Y_load_cast_fu_1508_p1 + tmp_45_mid2_v_reg_1983);

assign rect3_y2_fu_1529_p2 = (RECT3_HEIGHT_load_cast_fu_1525_p1 + rect3_y1_fu_1512_p2);

assign rects_sum_fu_1734_p2 = (tmp1_fu_1729_p2 + tmp_58_reg_2345);

assign result_x1 = tmp_84_fu_1898_p3;

assign result_x2 = (tmp_116_reg_1955 + tmp_84_fu_1898_p3);

assign result_y1 = tmp_87_reg_2071;

assign result_y2 = (tmp_116_reg_1955 + tmp_87_reg_2071);

assign row_3_fu_793_p2 = (ap_const_lv32_1 + row_reg_620);

assign s_1_fu_1060_p2 = (s_reg_666 + ap_const_lv5_1);

assign sh_assign_1_cast_cast_fu_1856_p1 = $signed(sh_assign_1_fu_1844_p3);

assign sh_assign_1_cast_fu_1852_p1 = $signed(sh_assign_1_fu_1844_p3);

assign sh_assign_1_fu_1844_p3 = ((isNeg_fu_1826_p3[0:0] === 1'b1) ? tmp_1_i_i_cast_fu_1840_p1 : sh_assign_fu_1820_p2);

assign sh_assign_2_fu_1100_p2 = ($signed(ap_const_lv9_181) + $signed(tmp_i_i_i6_cast2_fu_1096_p1));

assign sh_assign_3_cast_cast_fu_1136_p1 = $signed(sh_assign_3_fu_1124_p3);

assign sh_assign_3_cast_fu_1132_p1 = $signed(sh_assign_3_fu_1124_p3);

assign sh_assign_3_fu_1124_p3 = ((isNeg_3_fu_1106_p3[0:0] === 1'b1) ? tmp_1_i_i9_cast_fu_1120_p1 : sh_assign_2_fu_1100_p2);

assign sh_assign_fu_1820_p2 = ($signed(ap_const_lv9_181) + $signed(tmp_i_i_i_cast3_fu_1816_p1));

assign stage_accum_1_fu_1755_p2 = ($signed(below_1_cast_fu_1751_p1) + $signed(stage_accum_reg_677));

assign stage_accum_cast_cast_fu_1761_p1 = $signed(stage_accum_reg_677);

assign stage_feature_count_cast_fu_1190_p1 = STAGE_NUM_FEATURE_q0;

assign stage_thresh_cast_fu_1186_p1 = $signed(STAGE_THRESH_q0);

assign stddev_fu_994_p2 = (tmp_26_fu_970_p2 + tmp_29_fu_988_p2);

assign tmp1_fu_1729_p2 = (tmp_57_reg_2330 + tmp_59_fu_1723_p2);

assign tmp_100_fu_1565_p2 = (p_shl8_cast_fu_1545_p3 + p_shl9_cast_fu_1557_p3);

assign tmp_101_fu_1571_p2 = (tmp_168_fu_1535_p2 + tmp_100_fu_1565_p2);

assign tmp_102_fu_1606_p2 = (p_shl6_cast_fu_1586_p3 + p_shl7_cast_fu_1598_p3);

assign tmp_103_fu_1612_p2 = (tmp_168_fu_1535_p2 + tmp_102_fu_1606_p2);

assign tmp_104_cast_fu_910_p1 = tmp_78_fu_904_p2;

assign tmp_104_fu_1627_p2 = (tmp_173_fu_1623_p1 + tmp_102_fu_1606_p2);

assign tmp_105_cast_fu_954_p1 = tmp_79_reg_1997;

assign tmp_105_fu_1633_p2 = (tmp_173_fu_1623_p1 + tmp_100_fu_1565_p2);

assign tmp_106_cast_fu_931_p1 = tmp_80_fu_925_p2;

assign tmp_107_cast_fu_958_p1 = tmp_81_reg_2007;

assign tmp_116_fu_754_p1 = window_size[7:0];

assign tmp_117_fu_826_p1 = tmp_44_mid2_v_fu_820_p2[8:0];

assign tmp_119_cast_fu_1297_p1 = tmp_89_fu_1291_p2;

assign tmp_120_fu_838_p1 = tmp_44_mid2_v_fu_820_p2[10:0];

assign tmp_121_fu_864_p1 = tmp_45_mid2_v_fu_856_p3[8:0];

assign tmp_123_cast_fu_1338_p1 = tmp_91_fu_1332_p2;

assign tmp_124_cast_fu_1639_p1 = tmp_92_reg_2165;

assign tmp_125_cast_fu_1643_p1 = tmp_93_reg_2170;

assign tmp_126_fu_876_p1 = tmp_45_mid2_v_fu_856_p3[10:0];

assign tmp_127_fu_894_p1 = col_mid2_fu_804_p3[15:0];

assign tmp_129_cast_fu_1437_p1 = tmp_95_fu_1431_p2;

assign tmp_130_fu_898_p2 = (ap_const_lv16_18 + tmp_127_fu_894_p1);

assign tmp_131_fu_921_p1 = col_mid2_fu_804_p3[15:0];

assign tmp_133_cast_fu_1478_p1 = tmp_97_fu_1472_p2;

assign tmp_134_cast_fu_1661_p1 = tmp_98_reg_2240;

assign tmp_135_cast_fu_1665_p1 = tmp_99_reg_2245;

assign tmp_136_fu_1016_p2 = stddev_fu_994_p2 << ap_const_lv32_9;

assign tmp_137_fu_1022_p2 = stddev_fu_994_p2 << ap_const_lv32_6;

assign tmp_139_cast_fu_1577_p1 = tmp_101_fu_1571_p2;

assign tmp_143_cast_fu_1618_p1 = tmp_103_fu_1612_p2;

assign tmp_144_cast_fu_1689_p1 = tmp_104_reg_2295;

assign tmp_145_cast_fu_1693_p1 = tmp_105_reg_2300;

assign tmp_146_fu_1876_p3 = tmp_3_i_i_fu_1864_p2[ap_const_lv32_17];

assign tmp_149_fu_1156_p3 = tmp_3_i_i1_fu_1144_p2[ap_const_lv32_17];

assign tmp_150_fu_1237_p1 = rect1_x1_fu_1223_p2[15:0];

assign tmp_151_fu_1241_p1 = RECT1_WIDTH_q0;

assign tmp_152_fu_1377_p1 = rect2_x1_fu_1363_p2[15:0];

assign tmp_153_fu_1381_p1 = RECT2_WIDTH_q0;

assign tmp_154_fu_1517_p1 = rect3_x1_fu_1503_p2[15:0];

assign tmp_155_fu_1521_p1 = RECT3_WIDTH_q0;

assign tmp_156_fu_1255_p2 = (tmp_151_fu_1241_p1 + tmp_150_fu_1237_p1);

assign tmp_157_fu_1261_p1 = rect1_y2_fu_1249_p2[8:0];

assign tmp_158_fu_1273_p1 = rect1_y2_fu_1249_p2[10:0];

assign tmp_159_fu_1302_p1 = rect1_y1_fu_1232_p2[8:0];

assign tmp_160_fu_1314_p1 = rect1_y1_fu_1232_p2[10:0];

assign tmp_161_fu_1343_p1 = rect1_x1_fu_1223_p2[15:0];

assign tmp_162_fu_1395_p2 = (tmp_153_fu_1381_p1 + tmp_152_fu_1377_p1);

assign tmp_163_fu_1401_p1 = rect2_y2_fu_1389_p2[8:0];

assign tmp_164_fu_1413_p1 = rect2_y2_fu_1389_p2[10:0];

assign tmp_165_fu_1442_p1 = rect2_y1_fu_1372_p2[8:0];

assign tmp_166_fu_1454_p1 = rect2_y1_fu_1372_p2[10:0];

assign tmp_167_fu_1483_p1 = rect2_x1_fu_1363_p2[15:0];

assign tmp_168_fu_1535_p2 = (tmp_155_fu_1521_p1 + tmp_154_fu_1517_p1);

assign tmp_169_fu_1541_p1 = rect3_y2_fu_1529_p2[8:0];

assign tmp_170_fu_1553_p1 = rect3_y2_fu_1529_p2[10:0];

assign tmp_171_fu_1582_p1 = rect3_y1_fu_1512_p2[8:0];

assign tmp_172_fu_1594_p1 = rect3_y1_fu_1512_p2[10:0];

assign tmp_173_fu_1623_p1 = rect3_x1_fu_1503_p2[15:0];

assign tmp_1_i_i9_cast_fu_1120_p1 = $signed(tmp_1_i_i9_fu_1114_p2);

assign tmp_1_i_i9_fu_1114_p2 = (ap_const_lv8_7F - loc_V_7_fu_1072_p4);

assign tmp_1_i_i_cast_fu_1840_p1 = $signed(tmp_1_i_i_fu_1834_p2);

assign tmp_1_i_i_fu_1834_p2 = (ap_const_lv8_7F - loc_V_fu_1790_p4);

assign tmp_24_fu_962_p2 = ($signed(D_reg_2017) * $signed(D_reg_2017));

assign tmp_25_fu_966_p2 = ($signed(C_reg_2029) * $signed(C_reg_2029));

assign tmp_26_fu_970_p0 = integral_image_q1;

assign tmp_26_fu_970_p1 = integral_image_q1;

assign tmp_26_fu_970_p2 = ($signed(tmp_26_fu_970_p0) * $signed(tmp_26_fu_970_p1));

assign tmp_27_fu_976_p0 = integral_image_q0;

assign tmp_27_fu_976_p1 = integral_image_q0;

assign tmp_27_fu_976_p2 = ($signed(tmp_27_fu_976_p0) * $signed(tmp_27_fu_976_p1));

assign tmp_28_fu_982_p2 = (tmp_24_fu_962_p2 - tmp_25_fu_966_p2);

assign tmp_29_fu_988_p2 = (tmp_28_fu_982_p2 - tmp_27_fu_976_p2);

assign tmp_2_i_i1_fu_1140_p1 = $unsigned(sh_assign_3_cast_fu_1132_p1);

assign tmp_2_i_i_fu_1860_p1 = $unsigned(sh_assign_1_cast_fu_1852_p1);

assign tmp_30_fu_1000_p2 = ($signed(D_reg_2017) - $signed(C_reg_2029));

assign tmp_31_fu_1004_p1 = integral_image_q0;

assign tmp_31_fu_1004_p2 = ($signed(tmp_30_fu_1000_p2) - $signed(tmp_31_fu_1004_p1));

assign tmp_32_fu_1028_p2 = (tmp_136_fu_1016_p2 + tmp_137_fu_1022_p2);

assign tmp_33_fu_1034_p2 = ($signed(mean_fu_1010_p2) * $signed(mean_fu_1010_p2));

assign tmp_34_fu_1040_p2 = (tmp_32_fu_1028_p2 - tmp_33_fu_1034_p2);

assign tmp_35_fu_1054_p2 = ((s_reg_666 < ap_const_lv5_19) ? 1'b1 : 1'b0);

assign tmp_36_fu_1066_p1 = s_reg_666;

assign tmp_38_fu_1908_p2 = ((p_1_fu_162 == ap_const_lv8_0) ? 1'b1 : 1'b0);

assign tmp_3_i_i1_fu_1144_p2 = p_Result_9_fu_1084_p3 >> sh_assign_3_cast_cast_fu_1136_p1;

assign tmp_3_i_i_fu_1864_p2 = p_Result_s_fu_1804_p3 >> sh_assign_1_cast_cast_fu_1856_p1;

assign tmp_41_fu_1914_p2 = (($signed(total_stage_accum_cast_fu_1781_p1) > $signed(result_score_1_fu_166)) ? 1'b1 : 1'b0);

assign tmp_42_fu_1765_p2 = (($signed(stage_accum_reg_677) < $signed(stage_thresh_cast_reg_2077)) ? 1'b1 : 1'b0);

assign tmp_44_fu_1205_p1 = feature_index_1_phi_fu_692_p4;

assign tmp_44_mid2_v_fu_820_p2 = (tmp_44_mid2_v_v_cast_fu_812_p3 + row_reg_620);

assign tmp_44_mid2_v_v_cast_fu_812_p3 = ((exitcond1_fu_799_p2[0:0] === 1'b1) ? ap_const_lv32_19 : ap_const_lv32_18);

assign tmp_45_mid2_v_fu_856_p3 = ((exitcond1_fu_799_p2[0:0] === 1'b1) ? row_3_fu_793_p2 : row_reg_620);

assign tmp_48_fu_1650_p2 = (integral_image_q0 + tmp_47_reg_2225);

assign tmp_52_fu_1678_p2 = (integral_image_q0 + tmp_51_reg_2280);

assign tmp_56_fu_1712_p2 = (integral_image_q0 + tmp_55_reg_2315);

assign tmp_57_fu_1669_p0 = rect1_weight_reg_2265;

assign tmp_57_fu_1669_p2 = ($signed(tmp_57_fu_1669_p0) * $signed(rect1_sum_fu_1655_p2));

assign tmp_58_fu_1697_p0 = tmp_58_fu_1697_p00;

assign tmp_58_fu_1697_p00 = rect2_weight_reg_2270;

assign tmp_58_fu_1697_p2 = ($signed({{1'b0}, {tmp_58_fu_1697_p0}}) * $signed(rect2_sum_fu_1683_p2));

assign tmp_59_fu_1723_p0 = tmp_59_fu_1723_p00;

assign tmp_59_fu_1723_p00 = rect3_weight_reg_2275;

assign tmp_59_fu_1723_p2 = ($signed({{1'b0}, {tmp_59_fu_1723_p0}}) * $signed(rect3_sum_fu_1717_p2));

assign tmp_5_i_i1_fu_1150_p2 = tmp_i_i5_fu_1092_p1 << tmp_2_i_i1_fu_1140_p1;

assign tmp_5_i_i_fu_1870_p2 = tmp_i_i_fu_1812_p1 << tmp_2_i_i_fu_1860_p1;

assign tmp_60_fu_1739_p2 = (($signed(rects_sum_fu_1734_p2) < $signed(feature_thresh_cast_fu_1706_p1)) ? 1'b1 : 1'b0);

assign tmp_61_fu_1213_p2 = (ap_const_lv13_1 + feature_index_1_phi_fu_692_p4);

assign tmp_76_fu_850_p2 = (p_shl4_cast_fu_830_p3 + p_shl5_cast_fu_842_p3);

assign tmp_77_fu_888_p2 = (p_shl2_cast_fu_868_p3 + p_shl3_cast_fu_880_p3);

assign tmp_78_fu_904_p2 = (tmp_130_fu_898_p2 + tmp_76_fu_850_p2);

assign tmp_79_fu_915_p2 = (tmp_130_fu_898_p2 + tmp_77_fu_888_p2);

assign tmp_80_fu_925_p2 = (tmp_131_fu_921_p1 + tmp_76_fu_850_p2);

assign tmp_81_fu_936_p2 = (tmp_131_fu_921_p1 + tmp_77_fu_888_p2);

assign tmp_82_fu_1884_p1 = tmp_146_fu_1876_p3;

assign tmp_83_fu_1888_p4 = {{tmp_5_i_i_fu_1870_p2[ap_const_lv32_1E : ap_const_lv32_17]}};

assign tmp_84_fu_1898_p3 = ((isNeg_fu_1826_p3[0:0] === 1'b1) ? tmp_82_fu_1884_p1 : tmp_83_fu_1888_p4);

assign tmp_85_fu_1164_p1 = tmp_149_fu_1156_p3;

assign tmp_86_fu_1168_p4 = {{tmp_5_i_i1_fu_1150_p2[ap_const_lv32_1E : ap_const_lv32_17]}};

assign tmp_87_fu_1178_p3 = ((isNeg_3_fu_1106_p3[0:0] === 1'b1) ? tmp_85_fu_1164_p1 : tmp_86_fu_1168_p4);

assign tmp_88_fu_1285_p2 = (p_shl16_cast_fu_1265_p3 + p_shl17_cast_fu_1277_p3);

assign tmp_89_fu_1291_p2 = (tmp_156_fu_1255_p2 + tmp_88_fu_1285_p2);

assign tmp_90_fu_1326_p2 = (p_shl14_cast_fu_1306_p3 + p_shl15_cast_fu_1318_p3);

assign tmp_91_fu_1332_p2 = (tmp_156_fu_1255_p2 + tmp_90_fu_1326_p2);

assign tmp_92_fu_1347_p2 = (tmp_161_fu_1343_p1 + tmp_90_fu_1326_p2);

assign tmp_93_fu_1353_p2 = (tmp_161_fu_1343_p1 + tmp_88_fu_1285_p2);

assign tmp_94_fu_1425_p2 = (p_shl12_cast_fu_1405_p3 + p_shl13_cast_fu_1417_p3);

assign tmp_95_fu_1431_p2 = (tmp_162_fu_1395_p2 + tmp_94_fu_1425_p2);

assign tmp_96_fu_1466_p2 = (p_shl10_cast_fu_1446_p3 + p_shl11_cast_fu_1458_p3);

assign tmp_97_fu_1472_p2 = (tmp_162_fu_1395_p2 + tmp_96_fu_1466_p2);

assign tmp_98_fu_1487_p2 = (tmp_167_fu_1483_p1 + tmp_96_fu_1466_p2);

assign tmp_99_fu_1493_p2 = (tmp_167_fu_1483_p1 + tmp_94_fu_1425_p2);

assign tmp_fu_742_p2 = ($signed(ap_const_lv32_FFFFFFE8) + $signed(width));

assign tmp_i_i5_fu_1092_p1 = p_Result_9_fu_1084_p3;

assign tmp_i_i_fu_1812_p1 = p_Result_s_fu_1804_p3;

assign tmp_i_i_i6_cast2_fu_1096_p1 = loc_V_7_fu_1072_p4;

assign tmp_i_i_i_cast3_fu_1816_p1 = loc_V_fu_1790_p4;

assign tmp_s_fu_748_p2 = ($signed(ap_const_lv32_FFFFFFE8) + $signed(height));

assign total_stage_accum_1_fu_1770_p2 = ($signed(stage_accum_cast_cast_fu_1761_p1) + $signed(total_stage_accum_reg_642));

assign total_stage_accum_cast_fu_1781_p1 = $signed(total_stage_accum_reg_642);

assign val_assign_3_mid2_fu_1046_p1 = grp_fu_704_p2;

always @ (posedge ap_clk) begin
    feature_thresh_trunc_ext_cast_reg_2047[23:16] <= 8'b00000000;
    tmp_44_reg_2092[63:13] <= 51'b000000000000000000000000000000000000000000000000000;
end

endmodule //detect_face_cascade_classifier
