# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /afs/ece.cmu.edu/usr/junyec/Private/class/18500/FacialDetection/solution1/impl/verilog/detect_face.xdc

# IP: ip/detect_face_ap_fmul_0_max_dsp_32/detect_face_ap_fmul_0_max_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==detect_face_ap_fmul_0_max_dsp_32 || ORIG_REF_NAME==detect_face_ap_fmul_0_max_dsp_32}]

# IP: ip/detect_face_ap_uitofp_0_no_dsp_32/detect_face_ap_uitofp_0_no_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==detect_face_ap_uitofp_0_no_dsp_32 || ORIG_REF_NAME==detect_face_ap_uitofp_0_no_dsp_32}]

# IP: ip/detect_face_ap_fdiv_4_no_dsp_32/detect_face_ap_fdiv_4_no_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==detect_face_ap_fdiv_4_no_dsp_32 || ORIG_REF_NAME==detect_face_ap_fdiv_4_no_dsp_32}]

# IP: ip/detect_face_ap_fptrunc_0_no_dsp_64/detect_face_ap_fptrunc_0_no_dsp_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==detect_face_ap_fptrunc_0_no_dsp_64 || ORIG_REF_NAME==detect_face_ap_fptrunc_0_no_dsp_64}]

# IP: ip/detect_face_ap_fpext_0_no_dsp_32/detect_face_ap_fpext_0_no_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==detect_face_ap_fpext_0_no_dsp_32 || ORIG_REF_NAME==detect_face_ap_fpext_0_no_dsp_32}]

# IP: ip/detect_face_ap_dmul_2_max_dsp_64/detect_face_ap_dmul_2_max_dsp_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==detect_face_ap_dmul_2_max_dsp_64 || ORIG_REF_NAME==detect_face_ap_dmul_2_max_dsp_64}]
