# Generated by Django 2.1.5 on 2019-04-15 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_1', models.FileField(blank=True, upload_to='')),
                ('picture_2', models.FileField(blank=True, upload_to='')),
                ('picture_3', models.FileField(blank=True, upload_to='')),
                ('picture_4', models.FileField(blank=True, upload_to='')),
                ('picture_5', models.FileField(blank=True, upload_to='')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
